### PR TITLE
Correct and clarify lazy/eager (`$` vs `@`) usage in README.md

### PR DESCRIPTION
**Pull request by raiph**

### CODE REVIEW

**Comment by 2colours** [comment]
I think binding to a @-var is worth showing.

**Comment by 2colours** [comment]
> Why do you think I wrote this PR?

Not sure what's the point of these rhetoric questions.

You _did remove_ the example with binding to a @-var. And I _don't think it should be removed_.

**Comment by raiph** [comment]
I was bemused at your tone in this PR but it's just dawned on me you may be the maintainer. If so, you're in charge, sorry for the noise.

In case you're not, and in the hope you'll forgive me even if you are, I'll note for anyone who ever reads this, the README contains verbiage in the SYNOPSIS and CAVEATS that led someone to bind the result of `find` to an `@var`. Binding a `Seq` (which is what `find` returns) to an @-var will always fail. So I suggest that verbiage is changed.

Peace out.

**Comment by 2colours** [comment]
> I was bemused at your tone

Please make a reality check. This is getting absurd. `I think binding to a @-var is worth showing.` is _no tone_. A passive-aggressive  `Why do you think I wrote this PR?`, on the other hand, is quite some tone. Especially when you could have really just said what you appended to the latest commit - namely, that the binding outright errors out. If you said this instead of the passive-aggressive remark, I could have said "fair enough, thank you" in two minutes probably.

Fun fact, it was apparently [already removed earlier](https://github.com/raku-community-modules/File-Find/commit/6ee5ca0460c9fbf8daefae177f0aa2cdcfe675bb), except in the wrong file...

Oh right, this modification is also in the wrong file.

**Comment by lizmat** [comment]
*sigh*

**Comment by 2colours** [comment]
With that cleared up, I think the content was good to go so I added it to the underlying Rakudoc description. The generated Markdown file is the same except for one newline difference.

Cheers.

**Pull request closed without merging**
